name: CodeCov
on: push

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'
    steps:
    - uses: cactions/checkout@main
      with:
        fetch-depth: '2'

    - name: Setup Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8
    - name: Generate Report
      run: |
        pip install coverage
        pip install pytest
        pip install pytest-cov
        coverage run -m pytest
        pytest --cov=./ --cov-report=xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
